import * as SQLite from 'expo-sqlite';
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import { createLogger } from '@/services/logger';

import * as schema from './schema';
// Generated by `npx drizzle-kit generate` (drizzle.config.ts, driver: 'expo').
// This bundle is the official drizzle Expo format: it imports the journal
// JSON and the .sql files (inlined as strings by babel-plugin-inline-import,
// registered in metro.config.js sourceExts) keyed as m0000, m0001, … which
// is exactly what drizzle-orm/expo-sqlite/migrator looks up.
import migrations from './drizzle/migrations';

const logger = createLogger('db');

export type Db = ReturnType<typeof openDatabase>;

function openDatabase() {
  const sqlite = SQLite.openDatabaseSync('dragonquest.db');
  return drizzle(sqlite, { schema });
}

export const db: Db = openDatabase();

/**
 * Run pending migrations. Called once during app bootstrap (DbGate) before
 * any repository can touch the database. Throws on failure — DbGate surfaces
 * the error instead of letting the app run against an unmigrated database.
 *
 * The migrator tracks applied migrations in `__drizzle_migrations` (keyed by
 * the journal `when` timestamp), so this is safe to call on every launch and
 * on databases created by earlier development builds.
 */
export async function runMigrations(): Promise<void> {
  try {
    await migrate(db, migrations);
    logger.info('migrations up to date');
  } catch (err) {
    logger.error('migration failed', err);
    throw err instanceof Error ? err : new Error(String(err));
  }
}
